# Generated by Django 5.2.1 on 2025-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gare',
            name='statut',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
