# Generated by Django 5.2.1 on 2025-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_car_nombre_places_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='prix_voyage',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
