# Generated by Django 5.2.1 on 2025-06-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reservations', '0004_remove_voyage_prix_voyage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='administrateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels cet administrateur appartient.', related_name='admin_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='password',
            field=models.CharField(default='aubin', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Les permissions spécifiques de cet administrateur.', related_name='admin_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels cet utilisateur appartient.', related_name='client_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Les permissions spécifiques de cet utilisateur.', related_name='client_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
