# Generated by Django 5.2.1 on 2025-06-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reservations', '0005_remove_administrateur_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this admin belongs to.', related_name='admin_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='statut',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='admin_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this client belongs to.', related_name='client_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this client.', related_name='client_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='heure_arrivee_prevue',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='places_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
