# Generated by Django 5.2.1 on 2025-06-12 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_administrateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='heure_arrivee_prevue',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='places_disponibles',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
